### ISSUE TITLE
Pre-requirements not made clear in readme.md file.

### ISSUE THREAD

**Issue by Maxelon** [joyofpw/docker#1]
A very minor issue, but I came at this cold, did I "docker compose up" and things failed. Can I suggest a couple of lines in the readme to say that certain directories need to exist before running?
- ./src/backend
- ./database/mariadb/data
- ./config/php/pw

Did not take me too long to work out what was going on, so only a small issue to what has proved a great help. Many thanks.

**Comment by clsource** [comment]
Thanks. 
I maybe add a Makefile to automate the commands and ensure those dirs are present before compose up 👍
